version: "2"
run:
  concurrency: 4
  tests: false
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - funlen
    - gocognit
    - godot
    - godox
    - interfacebloat
    - nlreturn
    - tagalign
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    gosec:
      excludes:
        - G107
    nestif:
      min-complexity: 10
    staticcheck:
      checks:
        - all
        - -ST1003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - ^api/
      - ^pkg/lib/
      - ^api/docs\.go$
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - ^api/
      - ^pkg/lib/
      - ^api/docs\.go$
      - third_party$
      - builtin$
      - examples$
